Add django_coverage_plugin
WesternFriend/WF-website pull request #828
Opened 2023-07-30 22:32 UTC by sim-codes

#### Add django_coverage_plugin #663
I have configure the [django_coverage_plugin](https://github.com/nedbat/django_coverage_plugin) as stated by [brylie](https://github.com/brylie).

I could not run the `make compile-deps`, the MAKE on PC is throwing an error which I'm find it hard to fix.

2023-08-01 16:55 UTC, brylie commented
> I could not run the make compile-deps, the MAKE on my PC is throwing an error which I'm find it hard to fix.

Try merging the latest changes from the `main` branch into your branch. In `main`, I have switched from using Makefile to a simple Python script called `develop.py`. You can call `python develop.py compile-deps` to lock the latest dependency changes. 😄

2023-08-02 16:10 UTC, brylie requested changes
As you can see from the following traceback, our tests are now failing. Since getting tests to pass in continuous integration is an essential part of working in software teams, it is good practice to ensure open-source pull requests also pass CI.

```
Traceback (most recent call last):
  File "/home/runner/work/WF-website/WF-website/.venv/bin/coverage", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/runner/work/WF-website/WF-website/.venv/lib/python3.11/site-packages/coverage/cmdline.py", line 973, in main
    status = CoverageScript().command_line(argv)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/WF-website/WF-website/.venv/lib/python3.11/site-packages/coverage/cmdline.py", line 684, in command_line
    return self.do_run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/WF-website/WF-website/.venv/lib/python3.11/site-packages/coverage/cmdline.py", line 858, in do_run
    self.coverage.start()
  File "/home/runner/work/WF-website/WF-website/.venv/lib/python3.11/site-packages/coverage/control.py", line 6[18](https://github.com/WesternFriend/WF-website/actions/runs/5708714684/job/15526774011?pr=828#step:7:19), in start
    self._init()
  File "/home/runner/work/WF-website/WF-website/.venv/lib/python3.11/site-packages/coverage/control.py", line 332, in _init
    self._plugins = Plugins.load_plugins(self.config.plugins, self.config, self._debug)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/WF-website/WF-website/.venv/lib/python3.11/site-packages/coverage/plugin_support.py", line 55, in load_plugins
    __import__(module)
ModuleNotFoundError: No module named 'django_coverage_plugin'
```

Please follow the previous instructions to make sure our requirements.txt is updated so CI will pass. Otherwise, check out the contents of the `update-deps` command in the `develop.py` in our main branch and run those commands manually. Then, check in the resulting requirements files.

2023-08-03 10:21 UTC, sim-codes commented
I used the previous command `python develop.py compile-deps` as stated already.
Here is screenshot of the update on the requirements files and `pyproject.toml`
![image](https://github.com/WesternFriend/WF-website/assets/100477981/4e0f5bc9-4950-4d28-9ae6-1b9b4f63e4cf)

2023-08-03 15:05 UTC, brylie approved these changes

2023-08-03 15:05 UTC, merged