added possibility to feature books and list them at the top
WesternFriend/WF-website pull request #854
Opened 2023-08-28 05:54 UTC by ErnstBas

Hi @brylie  this is a draft solution for #823.

* I added a boolean `is_featured` field to models.py. 
* I amended the `products_index_page.html` template.

Some issues:

* It works, but not perfectly. When entering books in one go, they are grouped as expected 1) featured/non-featured and 2) alphabetically. But if I try to add other books later, they are added at the end. I have no solution yet.
* I added `null=True, blank=True` to the `is-featured` field. I hope this is ok.

Suggestions for improvement are welcome.

2023-08-30 21:08 UTC, ErnstBas commented
The problem with the order of the featured book has been resolved.

2023-09-05 14:19 UTC, brylie commented on store/models.py
> +    is_featured = models.BooleanField(default=False, null=True, blank=True)
Since this has a default, we don't need null or blank = True
```suggestion
    is_featured = models.BooleanField(default=False)
```

2023-09-05 14:26 UTC, brylie commented on store/templates/store/store_index_page.html
> +    {% regroup products|dictsort:"title" by is_featured as grouped_products %}
> Note that {% regroup %} does not order its input! 
> The easiest solution to this gotcha is to make sure in your view code that the data is ordered according to how you want to display it.
> https://docs.djangoproject.com/en/4.2/ref/templates/builtins/#regroup

This is a subtlety of the `regroup` tag, but the data need to be sorted by the grouping element.

```suggestion
    {% regroup products|dictsort:"is_featured" by is_featured as grouped_products %}
```

Also, the items can be sorted in the database query to leverage any database optimizations.

2023-09-05 14:33 UTC, brylie requested changes
This is close, but the items need to be sorted by `order_by` in order for the grouper to work correctly.

2023-09-06 17:11 UTC, ErnstBas commented on store/models.py
>          context["products"] = Product.objects.all()
Hi @Brylie, thank you for your constructive feed back. I appreciate that you took to time for this. I now realise I completely tunnel visioned on the `Product` class, overlooking the `order_by` options in the `StoreIndexPage` class. 

So, I tested your suggested code, but unfortunately that does not fix the ordering yet. I think we could solve this as follows:

We could order products also by title:
`context["products"] = Product.objects.all().order_by("-is_featured", "title")`

This permits to reduce the loops and conditionals in the HTML file to a single for loop and it solves the code duplication. And as I found out later, the ordering in the database is not case sensitive, like the HMTL code.

I will commit this.  Please let me know if this is ok.

2023-09-13 18:02 UTC, brylie commented on store/models.py
>          context["products"] = Product.objects.all()
Sounds good

2023-09-19 14:55 UTC, brylie reviewed
This is looking good. Is it ready for review?

2023-09-19 17:12 UTC, ErnstBas commented
Yes, please, let me know what you think.

2023-09-20 17:45 UTC, brylie approved these changes

2023-09-20 17:46 UTC, merged

2023-09-20 17:46 UTC, brylie commented
Looks great! Merged :-)